CREATE PROCEDURE [dbo].[spCustomers_Update]
	@id INT, 
    @short_name NVARCHAR(5), 
    @expedite NVARCHAR(1), 
    @qa NVARCHAR(25), 
    @qa_cost MONEY, 
    @is_sent BIT, 
    @is_recieved BIT, 
    @is_delivered BIT, 
    @billed MONEY, 
    @is_paid BIT, 
    @is_binder_purchased BIT, 
    @is_ship_normal BIT, 
    @is_ship_overnight BIT, 
    @mail_cost MONEY, 
    @binder_cost MONEY, 
    @is_binder_sent BIT, 
    @cost MONEY, 
    @profit MONEY, 
    @version NVARCHAR(20), 
    @update_date DATETIME, 
    @first_output_date DATETIME,
    @airline_notes NVARCHAR(MAX),
    @scan_rep NVARCHAR(25),
    @is_birdeye_sent BIT,
    @full_name NVARCHAR(100),
    @first_name NVARCHAR(25),
    @middle_name NVARCHAR(25),
    @last_name NVARCHAR(25),
    @call_sign NVARCHAR(25),
    @notes NVARCHAR(MAX),
    @email NVARCHAR(100),
    @interview_date DATETIME,
    @interview_airline NVARCHAR(25),
    @phone NVARCHAR(20),
    @Address NVARCHAR(100),
    @Address2 NVARCHAR(100),
    @City NVARCHAR(50),
    @State NVARCHAR(20),
    @Zip NVARCHAR(20),
    @country NVARCHAR(50),
    @is_military BIT,
    @branch NVARCHAR(100),
    @is_harrier BIT,
    @is_osprey BIT,
    @is_ip BIT,
    @is_commercial BIT,
    @is_121 BIT,
    @flies_for NVARCHAR(100),
    @is_corporate BIT,
    @is_contractor BIT,
    @flies_for_contractor NVARCHAR(100),
    @is_ga BIT,
    @is_faa_cert BIT,
    @winging_date DATE,
    @ifr_date DATE,
    @pic_date DATE,
    @solo_date DATE,
    @ppl_date DATE,
    @commercial_date DATE,
    @atp_date DATE,
    @cfi_date DATE,
    @cfii_date DATE,
    @mei_date DATE,
    @meii_date DATE,
    @registered_date DATE,
    @refferred NVARCHAR(100),
    @logbook_type NVARCHAR(MAX),
    @is_ratp BIT,
    @is_helo BIT,
    @is_navy_log BIT,
    @is_usaf_log BIT,
    @is_civ_log BIT,
    @cost_per_line MONEY,
    @process NVARCHAR(50),
    @POC NVARCHAR(50),
    @navy_pages INT,
    @navy_records INT,
    @ga_pages INT,
    @ga_records INT,
    @ga_large_pages INT,
    @ga_large_records INT,
    @usaf_pages INT,
    @usaf_records INT,
    @sent_date DATETIME,
    @received_date DATETIME,
    @due_date DATETIME,
    @completion_days FLOAT,
    @process_cost MONEY,
    @scans_received_date DATETIME,
    @meta_update DATETIME2(7)
AS
begin 
    update dbo.[customers] 
    set short_name = @short_name, expedite = @expedite, qa = @qa, qa_cost = @qa_cost, is_sent = @is_sent, is_received = @is_recieved, 
        is_delivered = @is_delivered, billed = @billed, is_paid = @is_paid, is_binder_purchased = @is_binder_purchased, is_ship_normal = @is_ship_normal, 
        is_ship_overnight = @is_ship_overnight, mail_cost = @mail_cost, binder_cost = @binder_cost, is_binder_sent = @is_binder_sent, cost = @cost, 
        profit = @profit, [version] = @version, update_date = @update_date, first_output_date = @first_output_date, airline_notes = @airline_notes,
        scan_rep = @scan_rep, is_birdeye_sent = @is_birdeye_sent, full_name = @full_name, first_name = @first_name, middle_name = @middle_name,
        last_name = @last_name, callsign = @call_sign, notes = @notes, email = @email, interview_date = @interview_date, interview_airline = @interview_airline,
        phone = @phone, [Address] = @Address, Address2 = @Address2, City = @City, [State] = @State, Zip = @Zip, country = @country, is_military = @is_military,
        branch = @branch, is_harrier = @is_harrier, is_osprey = @is_osprey, is_ip = @is_ip, is_commercial = @is_commercial, is_121 = @is_121, flies_for = @flies_for,
        is_corporate =@is_corporate, is_contractor= @is_contractor , flies_for_contractor = @flies_for_contractor, is_ga = @is_ga,
        is_faa_cert = @is_faa_cert, winging_date = @winging_date, ifr_date = @ifr_date, pic_date = @pic_date, solo_date = @solo_date, ppl_date = @ppl_date,
        commercial_date = @commercial_date, atp_date = @atp_date, cfi_date = @cfi_date, cfii_date = @cfii_date, mei_date = @mei_date, meii_date = @meii_date,
        register_date = @registered_date, referred = @refferred, logbook_type = @logbook_type, is_ratp = @is_ratp, is_helo = @is_helo,
        is_navy_log = @is_navy_log, is_usaf_log = @is_usaf_log, is_civ_log = @is_civ_log, cost_per_line = @cost_per_line, process = @process, POC = @POC,
        navy_pages = @navy_pages, navy_records = @navy_records, ga_pages = @ga_pages, ga_records = @ga_records, ga_large_pages = @ga_large_pages,
        ga_large_records = @ga_large_records, usaf_pages = @usaf_pages, usaf_records = @usaf_records, sent_date = @sent_date, received_date = @received_date,
        due_date = @due_date, completion_days = @completion_days, process_cost = @process_cost, scans_received_date = @scans_received_date, meta_update = @meta_update
    where id = @id;
end