CREATE PROCEDURE [dbo].[spCustomers_Insert]
	@id INT OUTPUT, 
    @short_name NVARCHAR(5), 
    @expedite NVARCHAR(1), 
    @qa NVARCHAR(25), 
    @qa_cost MONEY, 
    @is_sent BIT, 
    @is_recieved BIT, 
    @is_delivered BIT, 
    @billed MONEY, 
    @is_paid BIT, 
    @is_binder_purchased BIT, 
    @is_ship_normal BIT, 
    @is_ship_overnight BIT, 
    @mail_cost MONEY, 
    @binder_cost MONEY, 
    @is_binder_sent BIT, 
    @cost MONEY, 
    @profit MONEY, 
    @version NVARCHAR(20), 
    @update_date DATETIME, 
    @first_output_date DATETIME,
    @airline_notes NVARCHAR(MAX),
    @scan_rep NVARCHAR(25),
    @is_birdeye_sent BIT,
    @full_name NVARCHAR(100),
    @first_name NVARCHAR(25),
    @middle_name NVARCHAR(25),
    @last_name NVARCHAR(25),
    @call_sign NVARCHAR(25),
    @notes NVARCHAR(MAX),
    @email NVARCHAR(100),
    @interview_date DATETIME,
    @interview_airline NVARCHAR(25),
    @phone NVARCHAR(20),
    @Address NVARCHAR(100),
    @Address2 NVARCHAR(100),
    @City NVARCHAR(50),
    @State NVARCHAR(20),
    @Zip NVARCHAR(20),
    @country NVARCHAR(50),
    @is_military BIT,
    @branch NVARCHAR(100),
    @is_harrier BIT,
    @is_osprey BIT,
    @is_ip BIT,
    @is_commercial BIT,
    @is_121 BIT,
    @flies_for NVARCHAR(100),
    @is_corporate BIT,
    @is_contractor BIT,
    @flies_for_contractor NVARCHAR(100),
    @is_ga BIT,
    @is_faa_cert BIT,
    @winging_date DATE,
    @ifr_date DATE,
    @pic_date DATE,
    @solo_date DATE,
    @ppl_date DATE,
    @commercial_date DATE,
    @atp_date DATE,
    @cfi_date DATE,
    @cfii_date DATE,
    @mei_date DATE,
    @meii_date DATE,
    @registered_date DATE,
    @refferred NVARCHAR(100),
    @logbook_type NVARCHAR(MAX),
    @is_ratp BIT,
    @is_helo BIT,
    @is_navy_log BIT,
    @is_usaf_log BIT,
    @is_civ_log BIT,
    @cost_per_line MONEY,
    @process NVARCHAR(50),
    @POC NVARCHAR(50),
    @sent_date DATETIME,
    @received_date DATETIME,
    @due_date DATETIME,
    @completion_days FLOAT,
    @process_cost MONEY,
    @scans_received_date DATETIME
AS
begin 
    insert into dbo.[customers] (id, short_name, expedite, qa, qa_cost, is_sent, is_received, is_delivered, billed, is_paid, 
                                 is_binder_purchased, is_ship_normal, is_ship_overnight, mail_cost, binder_cost, is_binder_sent, cost, profit, 
                                 [version], update_date, first_output_date, airline_notes, scan_rep, is_birdeye_sent, full_name, first_name, 
                                 middle_name, last_name, callsign, notes, email, interview_date, interview_airline, phone, [Address], 
                                 Address2, City, [State], Zip, country, is_military, branch, is_harrier, is_osprey, is_ip, is_commercial, 
                                 is_121, flies_for, is_corporate, is_contractor, flies_for_contractor, is_ga, is_faa_cert, winging_date, ifr_date, 
                                 pic_date, solo_date, ppl_date, commercial_date, atp_date, cfi_date, cfii_date, mei_date, meii_date, register_date, 
                                 referred, logbook_type, is_ratp, is_helo, is_navy_log, is_usaf_log, is_civ_log, cost_per_line, process, POC, sent_date, 
                                 received_date, due_date, completion_days, process_cost, scans_received_date)
    
    values (@id, @short_name, @expedite, @qa, @qa_cost, @is_sent, @is_recieved, @is_delivered, @billed, @is_paid, 
            @is_binder_purchased, @is_ship_normal, @is_ship_overnight, @mail_cost, @binder_cost, @is_binder_sent, @cost, @profit, 
            @version, @update_date, @first_output_date, @airline_notes, @scan_rep, @is_birdeye_sent, @full_name, @first_name, 
            @middle_name, @last_name, @call_sign, @notes, @email, @interview_date, @interview_airline, @phone, @Address, 
            @Address2, @City, @State, @Zip, @country, @is_military, @branch, @is_harrier, @is_osprey, @is_ip, @is_commercial, 
            @is_121, @flies_for, @is_corporate, @is_contractor, @flies_for_contractor, @is_ga, @is_faa_cert, @winging_date, 
            @ifr_date, @pic_date, @solo_date, @ppl_date, @commercial_date, @atp_date, @cfi_date, @cfii_date, @mei_date,
            @meii_date, @registered_date, @refferred, @logbook_type, @is_ratp, @is_helo, @is_navy_log, @is_usaf_log,
            @is_civ_log, @cost_per_line, @process, @POC, @sent_date, @received_date, @due_date, @completion_days, @process_cost,
            @scans_received_date);
end
